name: Samuel Púčať
markdown: kramdown
permalink: /blog/:year/:month/:day/:title

gems:
    - jemoji
    - jekyll-sitemap
    - jekyll-timeago
    - jekyll-toc

collections:
  hobbys:
    output: true

